// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pilot.Infrastructure.Persistence.DbContexts;

#nullable disable

namespace Pilot.Infrastructure.Migrations
{
    [DbContext(typeof(PilotDbContext))]
    partial class PilotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LanguageReferee", b =>
                {
                    b.Property<int>("LanguagesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("RefereesId")
                        .HasColumnType("uuid");

                    b.HasKey("LanguagesId", "RefereesId");

                    b.HasIndex("RefereesId");

                    b.ToTable("LanguageReferee", "public");
                });

            modelBuilder.Entity("Pilot.Domain.Entities.Competition", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Competition", "public");
                });

            modelBuilder.Entity("Pilot.Domain.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Diaclect")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Language", "public");
                });

            modelBuilder.Entity("Pilot.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("RefereeId")
                        .HasColumnType("uuid");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocalTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisitorTeamId")
                        .HasColumnType("uuid");

                    b.HasKey("RefereeId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("LocalTeamId");

                    b.HasIndex("VisitorTeamId");

                    b.ToTable("Match", "public");
                });

            modelBuilder.Entity("Pilot.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RedCard")
                        .HasColumnType("integer");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("YellowCard")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Player", "public");
                });

            modelBuilder.Entity("Pilot.Domain.Entities.Referee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Referee", "public");
                });

            modelBuilder.Entity("Pilot.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Team", "public");
                });

            modelBuilder.Entity("LanguageReferee", b =>
                {
                    b.HasOne("Pilot.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pilot.Domain.Entities.Referee", null)
                        .WithMany()
                        .HasForeignKey("RefereesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pilot.Domain.Entities.Competition", b =>
                {
                    b.HasOne("Pilot.Domain.Entities.Team", null)
                        .WithMany("Competitions")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("Pilot.Domain.Entities.Match", b =>
                {
                    b.HasOne("Pilot.Domain.Entities.Competition", null)
                        .WithMany("Matches")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pilot.Domain.Entities.Team", "LocalTeam")
                        .WithMany("LocalMatchs")
                        .HasForeignKey("LocalTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pilot.Domain.Entities.Team", "VisitorTeam")
                        .WithMany("VisitorMatchs")
                        .HasForeignKey("VisitorTeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LocalTeam");

                    b.Navigation("VisitorTeam");
                });

            modelBuilder.Entity("Pilot.Domain.Entities.Competition", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Pilot.Domain.Entities.Team", b =>
                {
                    b.Navigation("Competitions");

                    b.Navigation("LocalMatchs");

                    b.Navigation("VisitorMatchs");
                });
#pragma warning restore 612, 618
        }
    }
}
